# Generated by Django 4.2.5 on 2023-09-27 04:41

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {

    "published": "A post that is available on the public site", 
    "draft": "A post only available to the author",
    "archived": "A post that is available on the archive view"}
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status (name=key, description=value) 
        status_obj.save()
class Migration (migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]
    operations = [
        migrations.RunPython (populate_status)
    ]